site_name: Python & Flask トレーニング
site_description: COBOL経験者向けPython & Flaskトレーニング教材
site_author: トレーニング運営

# モダンなカラーパレット
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/weather-night
        name: ダークモード
    - scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: ライトモード
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
  font:
    text: "IBM Plex Sans JP"
    code: "Fira Mono"

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - はじめに: index.md
  - Python基礎:
      - Pythonとは: python_intro.md
      - 環境セットアップ: python_env.md
      - 変数と型: python/python_basic_variables.md
      - 条件分岐: python/python_basic_if.md
      - ループ: python/python_basic_loop.md
      - 関数: python/python_basic_func.md
      - コレクション（リスト・辞書・セット）: python/python_basic_collection.md
      - ファイル操作: python/python_basic_file.md
      - エラー処理: python/python_basic_error.md
      - HTTPリクエスト: python/python_basic_http-requests.md
  - FastAPI入門:
      - FastAPI概要: fastapi/fastapi_intro.md
      - API開発: fastapi/fastapi_api.md
      - APIドキュメントの自動生成: fastapi/fastapi_api-document.md
  - Watson X Orchestrate:
      - Watson Xとは: watsonx/watsonx_intro.md
      - AI・生成AIの基礎: watsonx/watsonx_ai_basics.md
      - プロンプトエンジニアリング: watsonx/watsonx_prompt_engineering.md
      - 環境構築: watsonx/watsonx_setup.md
      - はじめてのエージェント: watsonx/watsonx_first_agent.md
      - ツール開発: watsonx/watsonx_tools.md
      - エージェント連携: watsonx/watsonx_collaboration.md
      - 実践演習: watsonx/watsonx_practice.md
      - ADKからWXOへのデプロイ: watsonx/watsonx_adk_to_wxo.md
      - 課題演習: watsonx/watsonx_homework.md
      - チャレンジ課題: watsonx/watsonx_challenge.md
  - Flask入門:
      - Flask概要: flask/flask_intro.md
      - Flask API開発: flask/flask_api.md
      - DB連携: flask/flask_db.md
      - エラーハンドリング: flask/flask_error.md
  - まとめ: general/summary.md
  - 追加課題: general/challenge.md
  - 付録: general/appendix.md 